### ISSUE TITLE
A way to list/check for the variables in the template

### ISSUE THREAD

**Issue by Atreyagaurav** [michaelr524/string_template#1]
Hey there, this is minimalistic and almost perfect. But is there any chance you'd consider adding a method to list the named variables in the template, or a way to do safe_render which would give `Result` with rendered string if all the variables are replaced, and Error otherwise.

**Comment by michaelr524** [comment]
Hello Dear @Atreyagaurav 
Thanks for your kind words and interest in this lib.
At the moment I can't devote time to add new features. However, pull requests are welcome.

**Comment by Atreyagaurav** [comment]
I understand, I did consider doing that, but then I searched packages in cargo again to make sure I'm not reinventing the wheel and found a package that was inspired by this package (https://github.com/hasezoey/new_string_template) that seems to have the features that I want so I shifted to that one for my use case.

**Comment by michaelr524** [comment]
Amazing!
